studySpec:
  metrics:
  - metricId: accuracy
    goal: MAXIMIZE
  parameters:
    
  # TODO

  algorithm: ALGORITHM_UNSPECIFIED # results in Bayesian optimization
trialJobSpec:
  workerPoolSpecs:  
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    containerSpec:
      imageUri: gcr.io/qwiklabs-gcp-01-9a9d18213c32/trainer_image:latest
      args:
      - --job_dir=gs://qwiklabs-gcp-01-9a9d18213c32-kfp-artifact-store/jobs/forestcover_tuning_20220330_131346
      - --training_dataset_path=gs://qwiklabs-gcp-01-9a9d18213c32-kfp-artifact-store/data/training/dataset.csv
      - --validation_dataset_path=gs://qwiklabs-gcp-01-9a9d18213c32-kfp-artifact-store/data/validation/dataset.csv
      - --hptune
